# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NrGytQzXV8B84TOyculcfufWIlvTw-9r
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

df = pd.read_csv('insurance_data.csv')
df.head(10) #we need first 10 data to analyse

df.shape   #checking how many coloumns and rows in dataset

plt.scatter(df[['age']],df[['bought_insurance']],marker = '+') #differnce of data using scattter plot

X_test     #checking the test sample

#spliting the data for train and test
X_train,X_test,y_train,y_test = train_test_split(df[['age']],df.bought_insurance,train_size = 0.8)

#using logistic regression for predicting
model = LogisticRegression()
model.fit(X_train,y_train)  #fiting the data into logistic regression

model.predict(X_test)         #prediction 0 = no , 1 = yes

model.score(X_test,y_test)       #accuracy

y_predicted = model.predict(X_test)        #creating object for prediction
y_predicted

model.predict_proba(X_test)                  #predicting probablity to buy insurance x = not likely , y = likely

Probablity = model.predict_proba(X_test)
Probablity
