# -*- coding: utf-8 -*-
"""LogisticRegression - 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pg-ENZo8HGfAGbuBg-1__pDBpMRDFrYi
"""

import  pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

df = pd.read_csv('exams.csv')
df = df.rename(columns={'pass': 'result'})
df

plt.scatter(df[['study_hours']],df[['pass']])

X_train,X_test,y_train,y_test = train_test_split(df[['study_hours']],df.result,train_size = 0.8)

model = LogisticRegression()
model.fit(X_train,y_train)

X_test

model.predict([[3.5]])

model.score(X_test,y_test)

probablity = model.predict_proba([[3.5]])
probablity
